### ISSUE TITLE
[Report] [iOS<13.4] Download button opens email dialog box

### ISSUE THREAD

**Issue by leoric23** [anaestheticsapp/logbook#15]
the "download" button on the summary page has the same functionality as the "email" button right next to it. both open the emailing dialogue

**Comment by anaestheticsapp** [comment]
This is an intended workaround for a bug in Safari in standalone mode. When opening a file in Safari on iOS < 13.4, it is impossible to navigate back to the app, hence, this feature was disabled for Safari and the email dialog box is shown instead.

This bug was **fixed in iOS 13.4** and the download button works as intended in iOS Safari 13.4 and above.

Maybe we should display a warning for iOS < 13.5 as older versions of Safari have numerous bugs and security issues.

Security: Unauthorised access to camera, screen and plaintext passwords (iOS <13.3)
https://www.ryanpickren.com/webcam-hacking
https://support.apple.com/en-gb/HT211104
https://support.apple.com/en-gb/HT210918

iOS PWAs using Service Workers freeze after being backgrounded (iOS 13.4)
https://bugs.webkit.org/show_bug.cgi?id=211018

IndexedDB errors:
https://bugs.webkit.org/show_bug.cgi?id=197050
Likely related issue https://github.com/anaestheticsapp/logbook/issues/14

**Comment by leoric23** [comment]
oh god, sorry for bringing up those outdated-OS related problems. i will update soon and not report until i did

**Comment by anaestheticsapp** [comment]
Definitly keep reporting. We can only test the latest iOS version so it's good to find out what the issues are in older versions of Safari as most users are still using them! It's also good to keep this documented on GitHub so that we can refer to previous issues and to make sure that Safari workarounds are not removed by accident.
